### ISSUE TITLE
When this library does not satisfy your requirements or does not work

### ISSUE THREAD

**Issue by Avamander** [aaronds/arduino-nrf24l01#9]
I'd recommend trying [nrf24.github.io/RF24/](https://nrf24.github.io/RF24/) (https://github.com/nRF24/RF24).

**Comment by GF-Huang** [comment]
Dead link.

**Comment by Avamander** [comment]
@GF-Huang 

> Dead link.

Fixed it.

**Comment by ishyaerospace** [comment]
can you please inform me on what you should do with the link provided because I dont really use github and I'm kind of blind right now

would be much appreciated, Thanks

Edit:
never mind I downloaded the .ZIP and I added it to library, It worked however it doesn't have mirf.h  
basically I am still getting the same error that there is no <mirf.h> file or folder

Edit:
I got the ZIP folder from the ZIP https://github.com/WayinTop and I took the Mirf folder out of the communication .ZIP folder then I turned the Mirf folder back into its own separate .ZIP folder and then uploaded it to Arduino's Library
